// <auto-generated />
namespace MvcOnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_add_departman : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_add_departman));
        
        string IMigrationMetadata.Id
        {
            get { return "202412111337147_mig_add_departman"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
